PREFIX ex: <http://example.org/europe#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
    ?country ex:gdpRank ?rank.
}
WHERE {
    {
        SELECT ?country (COUNT(?higherGdp) AS ?rank)
        WHERE {
            ?country a ex:Country ;
            ex:gdpPerCapitaUSD ?gdp.
            OPTIONAL {
                ?higherGdp a ex:Country ;
                ex:gdpPerCapitaUSD ?higherGdpValue.
                FILTER(?higherGdpValue > ?gdp)
            }
        }
        GROUP BY ?country
    }
}
