PREFIX ex:  <http://example.org/authors#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>  
PREFIX dbo: <http://dbpedia.org/ontology/>

CONSTRUCT {
  ?author ex:dbpediaIRI ?dbpediaIRI .
  ?author dbo:description ?description .
  ?author ex:filmProduced ?film .
  ?author ex:wikisite ?wikiLink .
}
WHERE {

  ?author a ex:author ;
          ex:wikidataId ?wikidataId .

  SERVICE <https://dbpedia.org/sparql> {

    ?dbpediaIRI owl:sameAs ?wikidataId ;
                dbo:description ?description ;
                dbo:wikiPageWikiLink ?wikiLink .

    FILTER(LANG(?description) = "es")

    OPTIONAL {
      ?film dbo:producer ?dbpediaIRI .
    }
  }
}
