PREFIX ex: <http://example.org/authors#>

CONSTRUCT {
    ?author ?propertyID ?o .
}

WHERE {
    ?author a ex:author ;
        ex:wikidataId ?wikidataId .

    SERVICE <https://query.wikidata.org/sparql> {
        ?wikidataId ?propertyID ?valueID .
   
        # Start with http://www.wikidata.org/entity/statement/
        FILTER(STRSTARTS(STR(?valueID), "http://www.wikidata.org/entity/statement/"))

        # Add statement to http://www.wikidata.org/prop/statement/XXXXX (?propertyID)
        BIND(IRI(REPLACE(STR(?propertyID), "http://www.wikidata.org/prop/", "http://www.wikidata.org/prop/statement/")) AS ?statementPropID)
        ?valueID ?statementPropID ?o .
    }

}
